# -*- coding: utf-8 -*-
"""1er Tarea_Colab

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IMEkBikyh6ET5IEzObn_6qiZafai7MJJ
"""

print("Ejecicio Bisiesto")
anio=int(input("Ingrese el año:"))
if(anio % 400 == 0) or (anio % 4 == 0) and (anio % 100 != 0):
  print("El año es Bisiesto")
else:
  print("El no año es Bisiesto")

# Pregunta al usuario su edad
edad = int(input("Por favor, ingresa tu edad: "))

# Comprueba si es mayor de edad
if edad >= 18:
    print("Eres mayor de edad. ¡Bienvenido!")

    # Pregunta al usuario si tiene experiencia previa en programación
    experiencia_programacion = input("¿Tienes experiencia previa en programación? (si / no): ")

    # Comprueba la respuesta sobre la experiencia en programación
    if experiencia_programacion.lower() == "si":
        print("Genial, puedes aplicar al puesto.")
    else:
        print("No puedes aplicar, pero siempre es un buen momento para empezar a aprender.")

    # Pregunta al usuario provicia de origen
    provincia_origen = input("¿En que provicia habitas?:")

else:
    print("Eres menor de edad. ¡Lo sentimos, acceso restringido!")

print("Ejecicio Meses 1=Enero, 2=Febrero ... 8=Agosto")
switcher = {
        1: "Enero",
        2: "Febrero",
        3: "Marzo",
        4: "Abril",
        5: "Mayo",
        6: "Junio",
        7: "Julio",
        8: "Agosto",
        9: "Septiembre",
        10: "Octubre",
        11: "Noviembre",
        12: "Diciembre" }

argumet = int(input("Ingrese un numero:"))
NombreDeMes = switcher.get(argumet,"Mes invalido")
print(NombreDeMes)

# se coloca un capital C, a un interes I (que ocila entre 0 y 100), durante M anios y se desea saber en cunato se habra convertido ese capital en M anios, sabiendo que es acumulativo.

# 1er paso, crear variables
print("Ejecicio Inversion")
C=-1
I=0
M=0

while(C<0) or (I<=0) or (I>=100) or (M<0):
  print("Introduce el capital, el interes y el tiempo apropiados")
  C=int(input("Capital:"))
  I=int(input("Interes:"))
  M=int(input("Tiempo en Años:"))

for i in range(M):
  C=C*(1+I/100)
  print("Monto", C,"Colones")

print("Digite un numero")
numero=int(input("Numero:"))

#hacerlo hasta que no aperezca un numero negativo
while numero>0:
  suma=0
  for i in range(1,numero+1):
    if(numero % i==0):
      suma=suma + i
  print(suma)
  numero=int(input("Numero:"))
# de 10 la suma de sus divisores es 1+2+5+10= 18