# -*- coding: utf-8 -*-
"""LAB3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vsR_GeJLVQlMlImH3U6nsNks15fkuaMj
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/CSVInvestigation.csv')
data=pd.DataFrame(df)
print(data)

#5 paises con mayor indice de criminalidad
dataFiltered=data.loc[(data['Series']=="Intentional homicide rates per 100,000")]
print(dataFiltered.sort_values(by=['Value'],ascending=False)[['Country','Value']].head(5))

#5 paises con menor indice de criminalidad
dataFiltered=data.loc[(data['Series']=="Intentional homicide rates per 100,000")]
print(dataFiltered.sort_values(by=['Value'],ascending=True)[['Country','Value']].head(5))

#el crimen mas repetido por pais para 2018
dataFiltered2018=data.loc[(data['Year']==2018)]
print(dataFiltered2018)
print(dataFiltered2018['Series'].value_counts())

#crimen con el porcentaje mas alto en cr en el annio 2005
dataFilteredCR=data.loc[(data['Country']=="Costa Rica")&(data['Year']==2005)]
print(dataFilteredCR)
print(dataFilteredCR.sort_values(by=['Value'],ascending=False)[['Country','Series','Value']])

#comparativa entre CR, NIC y PAN por medio de la tasa
registo=df.loc[(df["Country"]=="Costa Rica")|(df["Country"]=="Panama")|(df["Country"]=="Nicaragua")]
print(registo)

registro=df["Year"]
annio=registro.mode()
print(annio)

#Genero más afectado en crimenes en promedio en el año 2018.
print()
print()
print('H-Genero más afectado en crimenes en promedio en el año 2018')
dataFilteredByGender=dataFiltered2018.loc[((dataFiltered2018['Series']=="Percentage of male and female intentional homicide victims, Male")
|(dataFiltered2018['Series']=="Percentage of male and female intentional homicide victims, Female"))].groupby('Series')['Value']
print(dataFilteredByGender.mean())

#Genero más afectado en crimenes en promedio en el año 2018.

# Filtra los datos para obtener solo las filas correspondientes al año 2018 y los géneros masculino y femenino
data_filtered = data.loc[((data['Year'] == 2018) & ((data['Series'] == "Percentage of male and female intentional homicide victims, Male") | (data['Series'] == "Percentage of male and female intentional homicide victims, Female")))]

# Agrupa los datos por serie y calcula la media de los valores correspondientes a cada género
gender_totals = data_filtered.groupby('Series')['Value'].mean()
print(gender_totals)

# Encuentra el género con el valor máximo
most_affected_gender = gender_totals.idxmax()
print(most_affected_gender)
print("El género más afectado en los crímenes en el año 2018 es:", most_affected_gender)